apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-go
  name: simple-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-go
    spec:
      containers:
      - image:docker.io/rishabh1234/simple-go:ffeea4d98f656447b805c5c95b0072acd8ddce56
        name: simple-go
        resources: {}
status: {}
