kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: simple-go
  namespace: pipeline-test
spec:
  to:
    kind: Service
    name: simple-go
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
